{
	"schema_version": "1.6.0",
	"id": "CVE-2019-12243",
	"modified": "2024-09-03T02:24:52.290828Z",
	"published": "2019-06-05T15:29:01Z",
	"aliases": [
		"GHSA-6g5f-f5pm-mjrg"
	],
	"details": "Istio 1.1.x through 1.1.6 has Incorrect Access Control.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.0/AV:A/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H"
		}
	],
	"affected": [
		{
			"package": {},
			"ranges": [
				{
					"type": "GIT",
					"repo": "https://github.com/istio/istio",
					"events": [
						{
							"introduced": "82797c0c0649a3f73029b33957ae105260458c6e"
						},
						{
							"last_affected": "04850e14d38a69a38c16c800e237b1108056513e"
						}
					]
				}
			],
			"versions": [
				"1.1.0",
				"1.1.0-rc.6",
				"1.1.1",
				"1.1.2",
				"1.1.3",
				"1.1.4",
				"1.1.5",
				"1.1.6"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2019-12243.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://istio.io/about/notes/"
		},
		{
			"type": "EVIDENCE",
			"url": "https://istio.io/blog/2019/cve-2019-12243/"
		}
	]
}
